version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/app"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/tests_e2e"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/tests_e2e_app"
    schedule:
      interval: "weekly"
