name-template: 'v$NEXT_PATCH_VERSION 🌟'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    labels: ['feature','enhancement']
  - title: '🐛 Fixes'
    labels: ['bug','fix']
  - title: '🧪 Tests'
    labels: ['test']
  - title: '🧰 Maintenance'
    labels: ['chore','ci']
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
exclude-labels: ['skip-changelog']
template: |
  ## What’s new
  $CHANGES

  ## Thanks
  $CONTRIBUTORS
