name: Pre-release (RC)
on:
  push:
    tags:
      - 'v*-rc.*'
permissions:
  contents: write
jobs:
  prerelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Pack site
        run: zip -r site_bundle.zip site
      - name: Create GitHub pre-release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          generate_release_notes: true
          files: site_bundle.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
