name: Pytest
on:
  push:
    branches: [ main ]
  pull_request: {}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt
          pip install -r requirements-dev.txt
      - name: Run tests
        env:
          STREAMLIT_BROWSER_GATHER_USAGE_STATS: 'false'
        run: pytest -q --cov=app --cov-report=term-missing || pytest -q
