name: Security Scan — Trivy (strict)
on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:
jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Build app image
        run: docker build -t dora-app:scan ./app
      - name: Trivy image scan (fail on CRITICAL/HIGH)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: 'dora-app:scan'
          format: 'table'
          exit-code: '1'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
      - name: Trivy filesystem scan (fail on CRITICAL/HIGH)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
